### ISSUE TITLE
USER STORY: LR Admin; Track Poll; Archive Poll

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#10]
_In order to_ **track & maintain poll records** _as an_ **admin**, _I can_ **archive the expired poll & its data**.

# Acceptance Criteria:
- Option to close a successfully completed, tracked & recorded poll
- Closed poll & data automatically added to a list/database of all polls held to-date
-

## Probably its own User Story:
- Ability to search, duplicate & edit poll database; expedites generation of new polls, based on previous examples
-

# Tasks:
- [ ] Update UI: Create button HTMKL/CSS to close a successfully executed, tracked & recorded poll
- [ ] Update UI: Automatically add a closed poll to an on-screen list of all polls to-date
- [ ] Update test scripts & test functionality

#9
