### ISSUE TITLE
USER STORY: LR User; Leave Poll Response

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#3]
_In order to_ **provide feedback on a polled topic** _as a_ **user**, _I can_ **select & submit a poll response**.

# Acceptance Criteria:
- Display currently active poll question & selection of answers, in the form of an appropriate/required user-input capture method (radio, checkbox)
- A Submit button to enable submission, either immediately after answer selection or after subsequent anonymity & additional feedback options
-

# Tasks:
- [ ] Update UI: Create initial HTML/CSS for the base feature: #6 
- [ ] Display currently active poll question (or a test for init. dev purposes) #6 
- [ ] Create & populate appropriate user-input capture method HTML/CSS for poll responses #6
- [ ] Submit button to be enabled upon successful poll completion
- [ ] Update test scripts & test functionalty

#4 #5
