### ISSUE TITLE
USER STORY: LR User; Anonymous Polling Option

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#4]
_In order to_ **provide anonymous feedback** _as a_ **user**, _I can_ **have the option to hide my identity in the poll response**.

# Acceptance Criteria:
- Anonymity option provided as a checkbox
- Checkbox to be 'checked' by default
- Anonymity option appears next to Submit button
- If unchecked (user waives anonymity), submission to be updated to include user name
-

# Tasks:
- [ ] Update UI: poll html/css to include checkbox & submitter/username
- [ ] Create new field to track username
- [ ] Update controller function (is checked by default)
- [ ] Update test scripts & test functionality

#3 #5
