### ISSUE TITLE
USER STORY: LR User; Additional Feedback

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#5]
_In order to_ **leave additional feedback** _as a_ **user**, _I can_ **leave a comment before submitting the poll response**.

# Acceptance Criteria:
- Include text input field to accommodate any additional user feedback
- Input to be optional, i.e. not required for submission 
- Input should appear after the poll section and before the Submit button 
- Text field size/styling should retain/reflect current LR styling conventions
-

# Tasks:
- [ ] Update UI & style to suit site conventions: Create text input field HTML/CSS for additional user feedback (placeholder: 'Any other thoughts..? We'd like to hear them!'
- [ ] Update controller function (input not required for submission)
- [ ] Update test scripts & test functionality

#3 #4
