### ISSUE TITLE
USER STORY: LR Admin; Manage Poll; Set Poll Question

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#6]
_In order to_ **manage the poll** _as an_ **admin**, _I can_ **set the poll question**.

# Acceptance Criteria:
- Option to create & title a new poll
- Create & populate a suitable user-input capture method for poll responses (radio, checkbox)
- Ensure user-input method is 'required' for submission
- Option to reset poll (start again)
- Option to save/requirement to save poll to continue
-

# Tasks:
- [ ] Develop admin-only HTML/CSS to provide functionality to create & title a new poll
- [ ] Update UI: Create input fields HTML/CSS for poll question & responses
- [ ] Update controller function (is required for submission)
- [ ] Update UI: Create reset button to clear form as required
- [ ] Update UI: Create button to save & proceed
- [ ] Update test scripts & test fuctionality

#7 #8
