### ISSUE TITLE
USER STORY: LR Admin; Manage Poll; Publish Poll

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#7]
_In order to_ **manage the poll** _as an_ **admin**, _I can_ **publish the poll to the LR website**.

# Acceptance Criteria:
- Publish button enabled upon successful poll setup
- Clicking Publish displays & activates the poll on the LR website
-

# Tasks:
- [ ] Create Publish button HTML/CSS; enabled after successful poll setup
- [ ] Update UI: Enable poll HTML/CSS on live LR website
- [ ] Update test scripts & test functionality

#6 #8
