### ISSUE TITLE
USER STORY: LR Admin; Manage Poll; Set Poll Expiry

### ISSUE THREAD

**Issue by alfa23** [alfa23/first-agile-project#8]
_In order to_ **manage the poll** _as an_ **admin**, _I can_ **choose an expiry date to close and hide the poll**.

# Acceptance Criteria:
- Option for admin to schedule a day for the poll to expire @ 23:59 on that date
- Upon expiration poll is automatically hidden on the LR website
- A 'Stay Tuned, New Poll Soon!' appears if no other poll active
- Option appears after poll details, before Publish button
- Admin expiry date at least 3 days after current date & is not required for submission; allows non-restricted polling
-

# Tasks:
- [ ] Update Admin UI: Develop admin-only option to select & set an expiry/end-date functionality for polls
- [ ] Create JS function to validate expiry ≥3 days from current date
- [ ] Update Admin UI: When enabled the poll is automatically removed from the LR website upon expiry (23:59)
- [ ] Create job to check polls everyday @ 23:59 & Hide as necessary
- [ ] Update controller function (min 3 days, not required for submission)
- [ ] Update test scripts & test functionality

#6 #7
